# Generated by Django 2.0.3 on 2019-07-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('age_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение возраста')),
                ('phone_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение телефона')),
                ('sf_member', models.BooleanField(default=False, verbose_name='Участник SaleForce')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Смс код',
                'verbose_name_plural': 'Смс коды',
            },
        ),
    ]
