# Generated by Django 2.0.3 on 2019-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
